=== Mansikka/WarehouseManager/Warehouse.dtd
<!-- Our root element, warehouse.-->
<!ELEMENT warehouse (info, inbound, outbound, storage)>
<!ATTLIST warehouse name CDATA #REQUIRED >

<!--Warehouse information -->
<!ELEMENT info (manager, location)>

<!ELEMENT manager (#PCDATA)>
<!ELEMENT location (#PCDATA)>

<!-- Inbound are objects stated to arrive -->
<!ELEMENT inbound ( product* )>

<!-- Outbound are objects stated to depart -->
<!ELEMENT outbound ( product* )>

<!-- Storage tells us current items in the storage -->
<!ELEMENT storage ( product* )>

<!-- Our items, each has id, name and amount in stated section -->
<!ELEMENT product ( id, name, amount )>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== Mansikka/WarehouseManager/SCP Foundation/Location2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE warehouse SYSTEM "Warehouse.dtd">
<warehouse name="Provisional Containment Site-28">
	<info>
		<manager>Dr. Clef</manager>
		<location>Site-28</location>
	</info>
	
	<inbound>
	</inbound>
	
	<outbound>
		<product>
			<id>8</id>
			<name>SCP-1388</name>
			<amount>5</amount>
		</product>
	</outbound>
	
	<storage> 
		<product>
			<id>5</id>
			<name>SCP-602</name>
			<amount>1</amount>
		</product>
		<product>
			<id>6</id>
			<name>SCP-1229</name>
			<amount>6</amount>
		</product>
		<product>
			<id>7</id>
			<name>SCP-1669</name>
			<amount>1</amount>
		</product>
		<product>
			<id>8</id>
			<name>SCP-1388</name>
			<amount>5</amount>
		</product>
	</storage>
</warehouse>

=== Mansikka/WarehouseManager/XML/Warehouse14.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE warehouse SYSTEM "Warehouse.dtd">
<warehouse name="Warehouse 14">
	<info>
		<manager>Johnson</manager>
		<location>Utah</location>
	</info>
	
	<inbound>
		<product>
			<id>100</id>
			<name>Pack of Peanuts</name>
			<amount>2</amount>
		</product>
	</inbound>
	
	<outbound>
	</outbound>
	
	<storage> 
		<product>
			<id>99</id>
			<name>Wizard Lizard</name>
			<amount>1</amount>
		</product>
		<product>
			<id>122</id>
			<name>iPod 4th generation</name>
			<amount>1000</amount>
		</product>
		<product>
			<id>999</id>
			<name>Coffee package</name>
			<amount>2</amount>
		</product>
		<product>
			<id>1007</id>
			<name>THE Book</name>
			<amount>0</amount>
		</product>
	</storage>
</warehouse>

=== Mansikka/WarehouseManager/SCP Foundation/Location1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE warehouse SYSTEM "Warehouse.dtd">
<warehouse name="Humanoid Containment Site-06-3">
	<info>
		<manager>Dr. Mahong</manager>
		<location>Site-06-3</location>
	</info>
	
	<inbound>
		<product>
			<id>8</id>
			<name>SCP-1388</name>
			<amount>5</amount>
		</product>
	</inbound>
	
	<outbound>	
	</outbound>
	
	<storage> 
		<product>
			<id>1</id>
			<name>SCP-069</name>
			<amount>1</amount>
		</product>
		<product>
			<id>2</id>
			<name>SCP-706</name>
			<amount>1</amount>
		</product>
		<product>
			<id>3</id>
			<name>SCP-1669</name>
			<amount>1</amount>
		</product>
		<product>
			<id>4</id>
			<name>SCP-1702</name>
			<amount>1</amount>
		</product>
		<product>
			<id>21</id>
			<name>SCP-931</name>
			<amount>5</amount>
		</product>
	</storage>
</warehouse>

=== Mansikka/WarehouseManager/SCP Foundation/Location3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE warehouse SYSTEM "Warehouse.dtd">
<warehouse name="Biological Containment Site-66">
	<info>
		<manager>Mr. Anderson</manager>
		<location>Bio-Site-66</location>
	</info>
	
	<inbound>
	</inbound>
	
	<outbound>
		<product>
			<id>12</id>
			<name>SCP-806</name>
			<amount>3</amount>
		</product>
	</outbound>
	
	<storage> 
		<product>
			<id>9</id>
			<name>SCP-478</name>
			<amount>1</amount>
		</product>
		<product>
			<id>10</id>
			<name>SCP-569</name>
			<amount>6</amount>
		</product>
		<product>
			<id>11</id>
			<name>SCP-646</name>
			<amount>1</amount>
		</product>
		<product>
			<id>12</id>
			<name>SCP-806</name>
			<amount>2</amount>
		</product>		
		<product>
			<id>13</id>
			<name>SCP-886</name>
			<amount>1</amount>
		</product>		
		<product>
			<id>14</id>
			<name>SCP-1479</name>
			<amount>2</amount>
		</product>
	</storage>
</warehouse>

=== Mansikka/WarehouseManager/Warehouse13.xml
<?xml version="1.0"?>
<!DOCTYPE warehouse SYSTEM "Warehouse.dtd">
<warehouse name="Warehouse 13">
	<info>
		<manager>Agent Black</manager>
		<location>Area 51</location>
	</info>
	
	<inbound>
		<product>
			<id>3</id>
			<name>Arc of Covenant</name>
			<amount>1</amount>
		</product>
	</inbound>
	
	<outbound>
	</outbound>
	
	<storage> 
		<product>
			<id>4</id>
			<name>Holy Grail</name>
			<amount>1</amount>
		</product>
		<product>
			<id>1</id>
			<name>Excalibur</name>
			<amount>1</amount>
		</product>
		<product>
			<id>8</id>
			<name>Dragons Teeth</name>
			<amount>10</amount>
		</product>
		<product>
			<id>22</id>
			<name>Answer to Life, Universe and Everything</name>
			<amount>42</amount>
		</product>
	</storage>
</warehouse>

=== Mansikka/WarehouseManager/SCP Foundation/Location4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE warehouse SYSTEM "Warehouse.dtd">
<warehouse name="Site-19">
	<info>
		<manager>Mr. Anderson</manager>
		<location>Site-19</location>
	</info>
	
	<inbound>
		<product>
			<id>12</id>
			<name>SCP-806</name>
			<amount>3</amount>
		</product>
	</inbound>
	
	<outbound>
		<product>
			<id>16</id>
			<name>SCP-131</name>
			<amount>1</amount>
		</product>
		<product>
			<id>21</id>
			<name>SCP-931</name>
			<amount>5</amount>
		</product>
	</outbound>
	
	<storage> 
		<product>
			<id>15</id>
			<name>SCP-055</name>
			<amount>1</amount>
		</product>
		<product>
			<id>16</id>
			<name>SCP-131</name>
			<amount>2</amount>
		</product>
		<product>
			<id>17</id>
			<name>SCP-055</name>
			<amount>1</amount>
		</product>
		<product>
			<id>18</id>
			<name>SCP-173</name>
			<amount>1</amount>
		</product>
		<product>
			<id>19</id>
			<name>SCP-387</name>
			<amount>9001</amount>
		</product>
		<product>
			<id>20</id>
			<name>SCP-668</name>
			<amount>1</amount>
		</product>
		<product>
			<id>21</id>
			<name>SCP-931</name>
			<amount>31</amount>
		</product>
	</storage>
</warehouse>
