=== Mansikka/WarehouseManager/XML/Company.dtd
<!-- Our root element, company.-->
<!ELEMENT company (info, warehouses, actions)>

<!-- Info which contains data about company. -->
<!ELEMENT info 		(name,  manager, location)>

<!ELEMENT name 		(#PCDATA)>
<!ELEMENT manager 	(#PCDATA)>
<!ELEMENT location 	(#PCDATA)>

<!-- Inbound are objects stated to arrive -->
<!ELEMENT warehouses 	( warehouse+ )>

<!ELEMENT warehouse EMPTY >
<!ATTLIST warehouse file CDATA #REQUIRED >

<!-- Our actions, if the program is upgraded, this can easily be expanded -->
<!ELEMENT actions 	( action* )>

<!ELEMENT action 	EMPTY>
<!ATTLIST action type CDATA #REQUIRED >
<!ATTLIST action att  CDATA #REQUIRED >

=== Mansikka/WarehouseManager/XML/Company3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE company SYSTEM "Company.dtd">
<company>
	<info>
		<name>Merger Corp</name>
		<manager>Doc</manager>
		<location>Street 5</location>
	</info>
	<warehouses>
		<warehouse file="Warehouse13.xml" />
		<warehouse file="Warehouse14.xml" />
	</warehouses>
	<actions>
		<action type="merge" att="Storage" />
		<action type="sort" att="ascending" />
	</actions>
</company>

=== Mansikka/WarehouseManager/Compiled/XML/Company2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE company SYSTEM "Company.dtd">
<company>
	<info>
		<name>Big Babylon's sheep Company Ltd</name>
		<manager>Smithinson</manager>
		<location>Utah</location>
	</info>
	<warehouses>
		<warehouse file="Warehouse14.xml" />
	</warehouses>
	<actions>
		<act type="sort" att="decending" />
	</actions>
</company>

=== Mansikka/WarehouseManager/SCP Foundation/SCP.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE company SYSTEM "Company.dtd">
<company>
	<info>
		<name>SCP Foundation</name>
		<manager>O5 Committee</manager>
		<location>Classified</location>
	</info>
	<warehouses>
		<warehouse file="Location1.xml" />
		<warehouse file="Location2.xml" />
		<warehouse file="Location3.xml" />
		<warehouse file="Location4.xml" />
	</warehouses>
	<actions>		
		<act type="sort" att="decending" />
		<act type="merge" att="outbound" />		
	</actions>
</company>

=== Mansikka/WarehouseManager/Compiled/XML/Company3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE company SYSTEM "Company.dtd">
<company>
	<info>
		<name>Merger Corp</name>
		<manager>Doc</manager>
		<location>Street 5</location>
	</info>
	<warehouses>
		<warehouse file="Warehouse13.xml" />
		<warehouse file="Warehouse14.xml" />
	</warehouses>
	<actions>
		<act type="merge" att="Storage" />
		<act type="sort" att="ascending" />
	</actions>
</company>

=== Mansikka/WarehouseManager/Compiled/XML/Company.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE company SYSTEM "Company.dtd">
<company>
	<info>
		<name>SCP Foundation</name>
		<manager>O5</manager>
		<location>Classified</location>
	</info>
	<warehouses>
		<warehouse file="Warehouse13.xml" />
	</warehouses>
	<actions>
		<act type="sort" att="decending" />
	</actions>
</company>
